package {

    public class xconst {

        public static const sa = ":),:-),smile,M,:d,biggrin,M,;),;-),wink,M,:o,:-o,eek,M,:p,tongue,M,(cool),8-),cool,M,:@,mad,M,:s,confused,M,:$,redface,M,:(,:-(,frown,M,:'(,crying,M,|-),sleepy,M,:|,:-|,rolleyes,M,(*),star,M,:-*,kiss,M,:[,:-[,vampire,M,p-),pirate2,T,:3,goofy,M,:v,pacman,M,:c,chest,M,:f,furries,M,:^),sman,M";
        public static const Puzzle = {
            134:"snake",
            136:"space",
            140:"match",
            152:"maze",
            162:"code",
            176:"reverse",
            184:"zip",
            236:"slot"
        };
        public static const Game = {
            188:"doodlerace",
            192:"matchrace",
            194:"snakerace",
            200:"spacewar",
            224:"hearts",
            238:"switch",
            246:"darts",
            256:"zwhack"
        };
        public static const f_Deleted = 33554432;
		
		private static var stab:String = (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((("Main£" + "Delete message£") + "Visitors£") + "Friends£") + "Send message£") + "Get a Chat Box£") + "Chat Groups£") + "View help£") + "Web Link£") + "More smilies£") + "Turn sound on£") + "Turn sound off£") + "Click on $1 to change your name£") + "Go to $1 Group£") + "Help£") + "Change your picture£") + "Interact with $1£") + "If not auto linked copy this to your browser:£") + "Change your name, picture and home page£") + "Sign In£") + "Private message£") + "Go to home page:£") + "Member£") + "Moderator£") + "Owner£") + "Banned£") + "Click to start chat£") + "Click to stop chat£") + "Change background, add or change group. Add extra features.£") + "Put a Chat Box on your website£") + "To change your name or picture click on this: $1£") + "Sign Out£") + "Connecting...£") + "You haven't said anything for a while. Press Sign In to rejoin the chat.£") + "Edit Your Chat£") + "Press Sign In to start chatting. To be signed in automatically go to the profile page and select [Sign me in automatically].£") + "You have started the chat in another window. Press Sign In to restart in this window again.£") + "This is a $1 only chat, you can private chat an owner or moderator and ask to join.£") + "Enter a link, web page or search term£") + "Get Images£") + "Background:£") + "Enter Group name here -\nor select below:£") + "Chat Groups are shared chat rooms, like the lobby, but for a specific purpose. You can put them as a group tab on your chat box£") + "Create New Group£") + "Edit xat.com Chat Box£") + "OK£") + "Change Background£") + "Change Group£") + "Set any width and height. Promote your chat box. Get a Poll, Quiz and Slide Show£") + "Extra Features...£") + "Edit Your Chat Box£") + "Get Your Own Chat Box£") + "Loading images, please wait£") + "Preview Group£") + "Failed to find any images,\nplease try again.£") + "Sorry, chat edit is closed for maintenance.\nPlease try later£") + "Preview£") + "Click to use this image£") + "Profile£") + "New User...£") + "Name£") + "Picture£") + "Home Page£") + "Choose from hundreds of pictures on the web£") + "Use Your Own£") + "Sign me in automatically£") + "Cancel£") + "Go to home page:£") + "No home page£") + "Private Chat£") + "Start a private chat£") + "Private Message£") + "Send a private message£") + "Un-Friend£") + "Add as Friend£") + "Add/Remove as Friend£") + "Ignore£") + "Un-Ignore£") + "Ignore/Un-Ignore this user£") + "Kick£") + "Kick this user off as a warning.£") + "Ban£") + "Un-Ban£") + "Prevent this user from posting messages£") + "Make Member£") + "£") + "£") + "£") + "Make Moderator£") + "£") + "I have un-banned£") + "Go to friend's location:£") + "Get a Chat Box£") + "£") + "£") + "£") + "£") + "£") + "Connection Problem. You could try to start the chat again, sorry.£") + "Please do not share your password with anyone. xat will never ask for your password.£") + "Network Problem!£") + "Report Unfair Ban£") + "Return to Chat Box£") + "Find Another Group£") + "Copy Link£") + "Link Copied to Clipboard£") + "Please go to your browser and press Ctrl-V in the address box.£") + "You are£") + "On xat£") + "Online£") + "Offline£") + "Friend£") + "Ignored£") + "Reason for Ban:£") + "Reason:£") + "Duration:£") + "Hours£") + "(0 = forever)£") + "(maximum 6)£") + "I have banned $1 forever for no reason£") + "I have banned $1 for $2 hours for no reason£") + "I have banned $1 forever. Reason: $2£") + "I have banned $1 for $2 hours. Reason: $3£") + "I have kicked $1 Reason: $2£") + "You can't kick someone without a reason.£") + "You have been banned£") + "not added you as a friend£") + "$1 has Banned you£") + "I have made $1 a moderator£") + "on $1£") + "I have demoted $1£") + "Get£") + "I have made $1 a member£") + "I have un-membered $1£") + "Main Owner£") + "Make Guest£") + "Make Owner£") + "I have made $1 an owner£") + "I have made $1 a guest£") + "Get Stuff£") + "View xat.me£") + "Invite all your IM friends to this chat!£") + "Add IM friends. Start IM version of the chat.£") + "On App£") + "Start IM£") + "Start IM version of the chat£") + "Please sign into IM first£") + "$1 friends invited to chat£") + "Marry/Best Friend£") + "Transfer£") + "Divorce£") + "Give away xats and days£") + "Married to£") + "Best friends with£") + "Register...£") + "Register, log in, log out etc.£") + "On MSN£") + "On AIM£") + "subscriber£") + "registered£") + "BFF£") + "married£") + "Transfer of $1 xats and $2 days\nfrom $3 to $4 complete\n£") + "£") + "User not found£") + "Bad password£") + "User not confirmed registration email£") + "Not enough xats£") + "You have to have a partner to get divorced!£") + "You already have a partner!£") + "Partner not registered£") + "Partner already has a partner!£") + "Not enough days!£") + "Sorry: Can't transfer to free xats user£") + "System problem. Please try later.£") + "Error£") + "subscribers£") + "registered users£") + "members£") + "Turn radio off£") + "Turn radio on£") + "Enter message, your password and enter the amount to transfer.£") + "Enter message, your password and click your choice.£") + "Message£") + "Password£") + "Kiss£") + "Marry/BFF£") + "xats phishing protection: Transfer held for $1 days£") + "Gagged£") + "Powers£") + "Add Effects£") + "Add Special Effects to your Avatar (days required)£") + "Protect Deactivated!£") + "Protect Activated! - for the next $1 minutes new users will need to solve a captcha.£") + "I have booted $1 to $2. Reason: $3£") + "sinbin£") + "I have sinbinned $1£") + "Gag£") + "Mute£") + "I have $1 $2 for $3 hours for no reason£") + "I have $1 $2 for $3 hours. Reason: $4£") + "Muted£") + "Transfer to: $1£") + "Subscriber for:£") + "$1 days£") + "xats£") + "Get xats£") + "Click to buy£") + "days£") + "Marry:£") + "Best Friends Forever:£") + "Please wait...£") + "Get $1£") + "Make a Group£") + "WARNING! Do not share this link!£") + "You have been automatically logged out. Please log in again at xat.com/login£") + "Open Live Panel£") + "Live Mode: Send questions and comments by typing here£") + "Invite all MSN/AIM friends£") + "Add MSN/AIM friends£") + "Hide inappropriate words£") + "Get Married£") + "Get Divorced£") + "Give to $1£") + "Send a kiss£") + "Updated£") + "Safe Trade£") + "Offer£") + "Done£") + "Accept trade£") + "Trade complete£") + "Failed£") + "Confirm trade£") + "WARNING: Trade may be unfair! Continue?£") + "xats reserve limit exceeded.£") + "(Reduce trade value by $1 xats)£") + "Banished£") + "Group Power£") + "Assign or Unassign $1 to this chat group.£") + "$1 unassigned£") + "$1 assigned£") + "unassigning $1 failed (you haven't assigned one)£") + "assigned $1 failed (have none or already in use)£") + "Group Powers that are assigned to groups cannot be traded£") + "Close£") + "Dunce£") + "UnDunce£") + "Please check your email.£") + "Group to Boot to:£") + "Set Picture: £") + "I have finished a $1 hour $2 ban in $3 seconds£") + "celebrity£") + "Sorry, you don't have the power£") + "Sorry, group power is not assigned£") + "$1 has bought $2  a $3£") + "Notifications£") + "Give a friend a gift£") + "Gifts£") + "banned£") + "dunced£") + "Chat is in protect mode. Try later.£") + "Protect Activated!£") + "Foe£") + "Un-Foe£") + "Are you a human?£") + "awarded a badge to£") + "Naughty£") + "UnNaughty£") + "naughty stepped£") + "Put this chat group on your page£") + "Yellow£") + "UnYellow£") + "yellow carded£") + "Best friend£") + "The xat app has expired. Please update it now.£") + "Available£") + "red carded£") + "I have banned myself for $1 hours. Reason: $2£") + "RedCard£") + "UnRedCard£") + "Unknown hug£") + "Too many hugs£") + "You need a xat ID to use xat. Please log in or register.£") + "Connected to xat. To find a xat group, click groups on the menu£") + "NOT connected to xat. Click here to reconnect£") + "Notice: Waiting for push notification.£") + "Make£") + "You started the chat on another device£") + "Retry£") + "Language£") + "Get Powers£") + "FAQ£") + "Terms£") + "Good friend£") + "");
        private static var xtab:String = (((((((((((((((((((((("eek,:o,:-o,wow£" + "mad,:@,angry£") + "mischief£") + "nme£") + "no,n,fail£") + "redface£") + "think£") + "tongue,:p£") + "yes,y,ok£") + "smile,happy,fun,:),:-),ha£") + "wink,;),;-)£") + "frown,sad,unhappy,:(,:-(£") + "crying,cry,:'(£") + "sleepy,sleep,sleeping,tired,|-)£") + "biggrin,:d,laugh,laughing,lol,rofl,hehe£") + "confused,:s£") + "cool,8)£") + "crs,cross£") + "hello,hi,hey£") + "un£") + "doh,duh£") + "what,eh£") + "");
        //private static var htab:String = ((((((((((((((((((((((("BB How do I change my Name, Picture and Home Page?£" + "Click <o> YourName at the top of the user list on the right£") + "BB How do I get my own xat chat box?£") + "Click [Get a Chat Box] button on the bottom right.£") + "BB How do I find other people to chat to?£") + "Visit " + todo.usedomain + "/groups or click on the group chat tab£") + "BB How can I stay safe online?£") + "Go to " + todo.usedomain + "/safety.html for more information£") + "BB What do the colors on the user list mean?£") + "Green is online, red is offline, gold is owner, silver is moderator, blue is member£") + "BB How do I turn off automatically sign?£") + "Go to your profile page and un-check sign in automatically. You will have to click [Sign In] every time you visit a chat box to appear on the user list and to chat£") + "BB How can I get help with something else?£") + "Visit " + todo.usedomain + "/help or " + todo.usedomain + "/support£") + "£") + "BB FOR CHAT BOX OWNERS£") + "£") + "BB How do I change the background picture?£") + "Click [Edit Your Chat] button on the bottom right and press the [Background] button£") + "BB How do I add a chat group, add advanced features, make a members only chat or change the size of the chat box?£") + "Click [Edit Your Chat] and choose a group. For advanced features click [Extra Features...] button£") + "BB How do I get more people on my chat box?£") + "Tell your friends or people on groups chats about your site. If you get some people on your site it will get listed on our popular list " + todo.usedomain + "/popular and more and more will visit£") + "");
        //private static var htab:String = "BB   http://ixat.io/ v" + chat.cVersion + "£\tStaff: Andy, Daniel, Austin, Techy";
        private static var htab:String = ((((((((((((((((((((((("BB How do I change my name, picture and home page?£" + "Click <o> YourName at the top of the user list on the right£") + "BB How do I get my own xat chat box?£") + "Click [Get a Chat Box] button on the bottom right.£") + "BB How do I find other people to chat with?£") + "Visit " + todo.usedomain + "/groups or click on the group chat tab£") + "BB How can I stay safe online?£") + "Go to " + todo.usedomain + "/safety.html for more information£") + "BB What do the colors on the user list mean?£") + "Green is online, red is offline, orange is owner, white is moderator, blue is member£") + "BB How do I stop from signing in automatically?£") + "Go to your profile page and un-check sign in automatically. You will have to click [Sign In] every time you visit a chat box to appear on the user list and to chat£") + "BB How can I get help with something else?£") + "Visit " + todo.usedomain + "/help or " + todo.usedomain + "/support£") + "£") + "BB FOR CHAT BOX OWNERS£") + "£") + "BB How do I change the background picture?£") + "Click [Edit Your Chat] button on the bottom right and press the [Background] button£") + "BB How do I add a chat group, add advanced features, make a members only chat or change the size of the chat box?£") + "Click [Edit Your Chat] and choose a group. For advanced features click [Extra Features...] button£") + "BB How do I get more people on my chat box?£") + "Tell your friends or people on group chats about your site. If you get some people on your site it will get listed on our popular list " + todo.usedomain + "/popular and more and more will visit£") + "");
		public static var StringTable:Array;
        public static var HelpTable:Array;
        public static var ActionTable:Object;
        public static var ActionNames:Array;
        public static var n1 = "Baby,Booble,Bunker,Cuddle,Cutie,Doodle,Foofie,Gooble,Honey,Kissie,Lover,Lovey,Moofie,Mooglie,Moopie,Moopsie,Nookum,Poochie,Pookie,Schmoopie,Schnoogle,Schnookie,Schnookum,Smooch,Smoochie,Smoosh,Snoogle,Snoogy,Snookie,Snookum,Snuggy,Sweetie,Woogle,Woogy,Wookie,Wookum,Wuddle,Wuggy,Wunny,Bumble,Bump,Dip";
        public static var name1;
        public static var n2 = "Boo,Bunch,Bunny,Cake,Cakes,Cute,Darling,Dumpling,Dumplings,Face,Foof,Goo,Head,Kin,Kins,Lips,Love,Mush,Pie,Pook,Pums,Bumble,Bump,Dip";
        public static var name2;
        public static var p1 = "funky,boogie,cool,groove,divine,glory,swell,nifty,crazy,freak,wacky,quirky,weird,wild,strange,style,radical,urban,wicked";
        public static var pool1;
        public static var p2 = "town,zone,club,city,time,community,center,place,central,nation,state,district,jungle,land,realm,tribe,monkeys,junction,show,point";
        public static var pool2;
        public static var bw = "cunt,fuck,wanker,nigger,bastard,prick,bollocks,asshole,cyber,blowjob,blow job,clit,cock,wank,twat,vagina,pussy,whore,porn,penis,sperm,spunk,ejaculat,bitch";
        public static var badwords;
		public static var highwords;
        public static var kss = "Confetti,Hearts,Champagne,Argue,Cry,Hippo,Hearts,Paint,Surprise,Magic8ball,Airplane,Parachute,Dynamite,Lips,Bomb,Fireworks,Pull,Shark,Blood,Globe,Bugs,Grumpy,Snow,Ttth";
        public static var kssa:Array;
        public static var kssw = {
			Beer:542,
            Donut:542,
            Led:542,
            Photo:542,
            Marriage:241,
            Marry:241,
            Rings:241,
            Sunset:241,
            Hippod:269,
            Divorce:269,
            Divorced:269,
            Botd:269
        };
        public static var backs = {
            h:"heart",
            s:"square",
            x:"hexagon",
            c:"clear",
            o:"octogram",
            d:"diamond",
            b1:"apple",
            b2:"lemon",
            b3:"pear",
            b4:"fruit",
            b5:"orange",
            b6:"plum",
            b7:"banana",
            b8:"shirt",
            b9:"soccer",
            b10:"football",
            b11:"pkn",
            b12:"tomb",
            b13:"snowy",
            b14:"tree",
            b15:"stock",
            b16:"bulb",
            b17:"balloon",
            b18:"eggb",
            b19:"camo",
            b20:"blob",
            b21:"alienb",
            b22:"gkaoani",
            b23:"gkaliens",
            b24:"independence",
            b25:"usface",
            b26:"fish",
            b27:"crab",
            b28:"octopus",
            b29:"jellyfish",
            b30:"starfish",
            b31:"shrimp",
            b32:"sea",
            b33:"electrocute",
            b34:"flame",
            b35:"timebomb",
            b36:"ornament",
            b37:"ogre",
            b38:"frog",
            b39:"flower2",
            b40:"gkbear",
            b41:"gkkitty",
            b42:"gkpanda",
            b43:"sheriff",
            b44:"cdycorn",
            b45:"cdyback",
            b46:"zodiac",
            b47:"flower",
            b48:"snakeban",
            b49:"moonb",
            b50:"brain",
            b51:"kpeng",
            b52:"sbell",
            b53:"tabsc",
            b54:"peace",
            b55:"punch",
            b56:"noface",
            b57:"carve",
            b58:"bot4",
            b59:"kdog",
            b60:"goldb",
            b61:"mazeban",
            b62:"goldstar",
            b63:"snowman",
            b64:"santa",
            b65:"reindeer",
            b66:"reback",
            b67:"champagneback",
            b68:"can",
            b69:"kduckback",
            b70:"heartfx",
            b71:"heartfx2",
            b72:"heartfx3",
            b73:"monster",
            b74:"katback",
            b75:"ksheepback",
            b76:"pulsefxback",
            b77:"bbback",
            b78:"fzback",
            b79:"kbeeback",
            b80:"drip",
            b81:"doodlerace",
            b82:"aliback",
            b83:"kpigback",
            b84:"poback",
            b85:"dropback",
            b86:"spback",
            b87:"kmback",
            b88:"tv80",
            b89:"zombieback",
            b90:"kheartb",
            b91:"kmoback",
			b92:"eggsleep",
			b93:"kfox",
			b94:"kcow",
			b95:"skback",
			b96:"suback",
			b97:"germ",
			b98:"germ2",
			b99:"germ3",
			b100:"germ4",
			b101:"germ5",
			b102:"germ6",
			b103:"germ7",
			b104:"germ8",
			b105:"germ9",
			b106:"germ10",
			b107:"cacback",
			b108:"cuback",
			b109:"fruties",
			b110:"frapple",
			b111:"frbanana",
			b112:"frgrapes",
			b113:"frkiwi",
			b114:"frlemon",
			b115:"frmelon",
			b116:"frorange",
			b117:"frpear",
			b118:"frpineapple",
			b119:"frstrawberry",
			b120:"eggback",
			b121:"badge",
			b122:"cornback",
			b123:"sheepback",
			b124:"wmback",
			b125:"ccback",
			b126:"springleaf",
			b127:"sunflower2",
			b128:"snailb",
			b129:"eventstats",
			b130:"bfb",
			b131:"sprback",
			b132:"hamsterback"
        };
        public static var backsR;
        public static var effects = {
            i:"invert",
            m:"mirror",
            y:"cycle",
            f:"fade"
        };
        public static var effectsR;
        public static var hugs = {};
        public static var hugsR;
        public static var colorc = {
            r:1,
            g:1,
            b:1
        };
        public static var topsh = {
			putears:35,
			puspray:35,
			pusleep:35,
			pushim:35,
			pufit:35,
			pueyes2:35,
			pueyes:35,
			pudizzy:35,
			pucry:35,
			pucheer:35,
            loser:37,
            rockon:37,
            palms:37,
            thumbsup:37,
            thumbsdown:37,
            flip:37,
            shh:37,
            bye:37,
            hug:37,
            clap:37,
            backoff:37,
            hehe:37,
            hmm:37,
            crazy:37,
            ono:37,
            shrug:37,
            hairm2:38,
            hairm3:38,
            emo:38,
            nrd:38,
            punk:38,
            hairf2:39,
            hairf3:39,
            hairf4:39,
            g1:39,
            goth:39,
			noface:40,
            ninja:42,
            cb:42,
            police:42,
            nurse:42,
            jester:42,
            sphinx:42,
            dhat:42,
            crown:42,
            partyhat:42,
            facemask:42,
            sherlock:42,
            prop:42,
            grad:42,
            dunce2:42,
            straw:42,
            ribbon:42,
            halo:45,
            cloud:45,
            pray:45,
            apple:48,
            lemon:48,
            pear:48,
            orange:48,
            plum:48,
            banana:48,
            shirt:49,
            soccer:49,
            football:49,
            shirts:49,
            ball:49,
            bb:49,
            foam:49,
            weight:49,
            trophy:49,
            helmet:49,
            cupw:49,
            pknlaugh:52,
            tort:52,
            pkn:52,
            wh:52,
            frk:52,
            mmy:52,
            cdn:52,
            grim:52,
            tomb:52,
            bat:52,
            ghost:52,
            dig:52,
            die:52,
            hypno:53,
            dizzy:53,
            rage:53,
            headband:53,
            fan:53,
            comeon:53,
            grin:53,
            grump:53,
            tear:53,
            awe:53,
            doh:53,
            pouty:53,
            maniac:53,
            squint:53,
            ahhh:53,
            quiver:53,
            haira1:53,
            haira2:53,
            haira3:53,
            haira4:53,
            haira5:53,
            astro:53,
            haira6:53,
            haira7:53,
            haira8:53,
            haira9:53,
            haira10:53,
            pilgrimm:55,
            pilgrimf:55,
            indian:55,
            indian2:55,
            indian3:55,
            chef:55,
            dining:55,
            feast2:55,
            eatleg:55,
            snows:56,
            beard:57,
            bell:57,
            cane:57,
            ches:57,
            elf:57,
            give:57,
            pole:57,
            sack:57,
            sball:57,
            scarf:57,
            sdeer:57,
            sfeet:57,
            shiver:57,
            sledge:57,
            slist:57,
            smound:57,
            spull:57,
            stock:57,
            tree:57,
            wreath:57,
            xb1:57,
            xb4:57,
            skiss:57,
            bulb:57,
            sgift:57,
            beat:62,
            bheart:62,
            cupid:62,
            card:62,
            hug2:62,
            hug3:62,
            ilu:62,
            lhand:62,
            ring:62,
            rose:62,
            rose2:62,
            pce:31,
            cd:31,
            sleep:31,
            fs:31,
            shift1:63,
            pawn1:63,
            bff1:63,
            frnt1:63,
            hat1:63,
            hat3:63,
            glow1:63,
            snows1:63,
            wb1:63,
            dunce1:63,
            badge1:63,
            fwp1:63,
            naughty1:63,
            yellow1:63,
			red1:63,
            balloon:65,
            bride:65,
            cake:65,
            phat:65,
            clink:65,
            pdance:65,
            pdance2:65,
            pdance3:65,
            groom:65,
            photo:65,
            popper:65,
            toast:65,
            clover2:66,
            drink:66,
            igirl:66,
            iman:66,
            pot:66,
            rainbow:66,
            shi:66,
            tap:66,
            drum:66,
            bagpipes:66,
            basket:68,
            bunny:68,
            bunny2:68,
            chick:68,
            egg2:68,
            eggb:68,
            paintegg:68,
            kbiggrin:72,
            kclap:72,
            kconfused:72,
            kcool:72,
            kcrying:72,
            kdizzy:72,
            keek:72,
            keyerub:72,
            kfit:72,
            kfrown:72,
            kglare:72,
            khehe:72,
            khello:72,
            khug:72,
            kkiss:72,
            klove:72,
            kmad:72,
            kmischief:72,
            knod:72,
            krant:72,
            kredface:72,
            ksad:72,
            ksleepy:72,
            ksmile:72,
            ksmirk:72,
            kstraight:72,
            kstruggle:72,
            ktongue:72,
            kun:72,
            kwink:72,
            acrobat:71,
            balloonart:71,
            cannon:71,
            clown:71,
            eleride:71,
            fireblow:71,
            firewand:71,
            highwire:71,
            uniwire:71,
            juggler:71,
            lion:71,
            splat:71,
            tamer:71,
            uni:71,
            unirope:71,
            wheel:71,
            camo:73,
            coastguard:73,
            drillserg:73,
            gasmask:73,
            m1h:73,
            marine:73,
            pilot:73,
            sailor:73,
            sailor2:73,
            salute:73,
            smoke:73,
            kachat:76,
            kacrazy:76,
            kafang:76,
            kafill:76,
            kagab:76,
            kagrin:76,
            kagsp:76,
            kalook:76,
            kao:76,
            kaoo:76,
            kapunch:76,
            kaswt:76,
            katalk:76,
            katear:76,
            katears:76,
            kaum:76,
            kaupset:76,
            kawink:76,
            alien2:77,
            alienb:77,
            beam:77,
            blob:77,
            borg:77,
            cylon:77,
            jetpack:77,
            laser:77,
            vial:77,
            vr:77,
            ufo:77,
            cheerleader:78,
            horn:78,
            pennant:78,
            corndog:78,
            vuvu:78,
            fish:82,
            fish2:82,
            fish3:82,
            bubbles:82,
            crab:82,
            diver:82,
            dolphin:82,
            jellyfish:82,
            octopus:82,
            shrimp:82,
            starfish:82,
            turtle:82,
            weed:82,
            bonk:83,
            burp:83,
            crazy2:83,
            dopey:83,
            impact:83,
            irked:83,
            itchy:83,
            mischief2:83,
            nose:83,
            raspberry:83,
            rolleye:83,
            spit:83,
            string:83,
            abe:87,
            bbq:87,
            flagwave:87,
            fwlaunch:87,
            glowstick:87,
            liberty:87,
            sparkler:87,
            starbounce:87,
            starburst:87,
            starring:87,
            tiphat:87,
            usface:87,
            usss:87,
            beachbbq:89,
            cooler:89,
            efan:89,
            fishing:89,
            frisbee:89,
            goggles:89,
            kayak:89,
            laytowl:89,
            pina:89,
            sanddig:89,
            sandplay:89,
            bands:89,
            towl:89,
            waterbottle:89,
            waterskii:89,
            biker:90,
            slingshot:90,
            thief:90,
            fbomb:90,
            liar:90,
            mist:92,
            franken:92,
            goblin:92,
            knife:92,
            pkncut:92,
            spider:92,
            triclops:92,
            vamp:92,
            warewolf:92,
            hit:93,
            dodge:93,
            lob:93,
            mobounce:93,
            moring:93,
            campfire:97,
            canopy:97,
            compass:97,
            firstaid:97,
            hangglider:97,
            hunting:97,
            lantern:97,
            map:97,
            marshmallow:97,
            iceaxe:97,
            swing:97,
            waterskiing:97,
            zipline:97,
            smokes:97,
            asif:99,
            one:99,
            heartburst:99,
            heartbounce:99,
            noway:99,
            duck:101,
            electrocute:101,
            eyepop:101,
            flamed:101,
            lookaround:101,
            scream:101,
            wow:101,
            dazed:101,
            hazey:101,
            drool:101,
            footmouth:101,
            mindblow:101,
            misspeak:101,
            relieved:101,
            uvula:101,
            arc:101,
            butterfly:102,
            fcrown:102,
            fhair:102,
            fhat:102,
            flower2:102,
            frog:102,
            fwings:102,
            heartwand:102,
            mushrooms:102,
            shards:102,
            kbawe:104,
            kbcold:104,
            kbcry:104,
            kbdance:104,
            kbpunch:104,
            kbsad:104,
            kbscream:104,
            kbweep:104,
            kbwink:104,
            kbyawn:104,
            explode:105,
            facepalm:105,
            bite:105,
            hissyfit:105,
            mutter:105,
            potstir:105,
            pullhair:105,
            raging:105,
            ticked:105,
            yell:105,
            flame:105,
            grumpy2:105,
            headache:105,
            timebomb:105,
            uangel:107,
            udemon:107,
            uevil:107,
            uhappy:107,
            ulook:107,
            uthink:107,
            usad:107,
            uscratch:107,
            usmile:107,
            utongue:107,
            uwink:107,
            carolers:96,
            decortree:96,
            giftdrop:96,
            giftrattle:96,
            gingerbread:96,
            pullsled:96,
            antler:96,
            shovel:96,
            accident:96,
            snowboard:96,
            snowfight:96,
            snowm:96,
            xface:96,
            snowmobile:96,
            ornament:96,
            earmuffs:96,
            snowglobe:96,
            cold:96,
            freezing:96,
            snowover:96,
            snowangel:96,
            windy:96,
            icecube:96,
            bowleat:98,
            burger:98,
            burgerlook:98,
            candycorn:98,
            carrot:98,
            cherry:98,
            chicken:98,
            chili:98,
            chipeat:98,
            coffeesplash:98,
            donut:98,
            eatspagetti:98,
            eattakeout:98,
            eggcook:98,
            eggplant:98,
            fortunecookie:98,
            fries:98,
            icecream:98,
            icecreameat:98,
            peanut:98,
            popcorn:98,
            pretzel:98,
            soupeat:98,
            spam:98,
            stirpan:98,
            takeout:98,
            thinkfood:98,
            toast2:98,
            pizza:98,
            kkbiggrin:110,
            kkconfused:110,
            kkcool:110,
            kkcrying:110,
            kkd:110,
            kkdance:110,
            kkdead:110,
            kkeek:110,
            kkfrown:110,
            kkhide:110,
            kkhug:110,
            kkmad:110,
            kknme:110,
            kkpaws1:110,
            kkpaws2:110,
            kkpaws3:110,
            kkredface:110,
            kkscn:110,
            kkshock:110,
            kksleepy:110,
            kksmile:110,
            kkstraightface:110,
            kkstruggle:110,
            kktongue:110,
            kkun:110,
            kkwary:110,
            kkwink:110,
            kkx3:110,
            kkxd:110,
            kkyawn:110,
            axe:111,
            darkeyes:111,
            dragon:111,
            flail:111,
            hole:111,
            helmet2:111,
            medusa:111,
            orcm:111,
            elf2:111,
            ogre:111,
            orcf:111,
            invis:111,
            scroll:111,
            slash:111,
            smskull:111,
            sword:111,
            wizard:111,
            daggers:113,
            electro:113,
            epi:113,
            fireball:113,
            flying:113,
            genie:113,
            iceman:113,
            invisi:113,
            jekyl:113,
            maddr:113,
            telekin:113,
            amazon:113,
            upaway:113,
            ripshirt:113,
            doggy:116,
            giraffe:116,
            goat:116,
            lion2:116,
            monkey:116,
            mouse:116,
            panda2:116,
            raccoon:116,
            sheep:116,
            unicorn:116,
            disco:117,
            dj:117,
            drums:117,
            flute:117,
            guitar:117,
            harp:117,
            piano:117,
            trumpet:117,
            violin:117,
            zippo:117,
            kpfit:118,
            kpembarassed:118,
            kppaws:118,
            kpd:118,
            kpannoyed:118,
            kppaws2:118,
            kplove:118,
            kpjoy:118,
            kpcrying:118,
            kphurt:118,
            blownose:119,
            chill:119,
            cough:119,
            icepack:119,
            sickface:119,
            sneeze:119,
            soup:119,
            thermometer:119,
            crutches:119,
            feint:119,
            cough2:119,
            headknock:119,
            crutches:119,
            sweats:119,
            coy:108,
            flirt:108,
            freehugs:108,
            heartbeat:108,
            heartblow:108,
            ihu:108,
            lovedraw:108,
            ucute:108,
            uhot:108,
            cringe:121,
            shake:121,
            shocking:121,
            envy:122,
            gluttony:122,
            greed:122,
            lust:122,
            pride:122,
            sloth:122,
            wrath:122,
            whip:123,
            turban:123,
            tophat:123,
            tinfoil:123,
            sombrero:123,
            paperbag:123,
            paperbag2:123,
            grandpa:123,
            grandma:123,
            glassesslip:123,
            disguise:123,
            curlers:123,
            braces:123,
            blindfold:123,
            beret:123,
            undertaker:124,
            sheriff:124,
            ropeg:124,
            ropeb:124,
            push:124,
            prospector:124,
            outlaw:124,
            native:124,
            bullride:124,
            bartender:124,
            officeworker:125,
            driver:125,
            doctor:125,
            chef2:125,
            burgerflipper:125,
            blacksmith:125,
            astronaut:125,
            teacher:125,
            stewardess:125,
            shepherd:125,
            scientist:125,
            plumber:125,
            paperboy:125,
            miner:125,
            mechanic:125,
            judge:125,
            journalist:125,
            gardener:125,
            fortuneteller:125,
            fireman:125,
            icman:128,
            lifeguard:128,
            lotion:128,
            metaldetect:128,
            sandbury:128,
            sandfun:128,
            shkhat:128,
            sunburn:128,
            surf:128,
            tanning:128,
            candy:129,
            cdycorn:129,
            cdyback:129,
            donuteat:129,
            eatchoco:129,
            floss:129,
            gum:129,
            lolipop:129,
            mm:129,
            aries:131,
            taurus:131,
            gemini:131,
            cancer:131,
            leo:131,
            virgo:131,
            libra:131,
            scorpio:131,
            sagittarius:131,
            capricorn:131,
            aquarius:131,
            pisces:131,
            fangry:132,
            fcry:132,
            fcool:132,
            feek:132,
            fconfused:132,
            ftongue:132,
            fredface:132,
            fsleepy:132,
            fbiggrin:132,
            fsad:132,
            fwink:132,
            eclipse:133,
            meteorite:133,
            nasa:133,
            radiotele:133,
            rocket:133,
            satellite:133,
            saucer:133,
            shuttle:133,
            space:133,
            telescope:133,
            sncool:134,
            sneek:134,
            snredface:134,
            snconfused:134,
            snfrown:134,
            snbiggrin:134,
            snangry:134,
            snsleepy:134,
            sncry:134,
            snsmile:134,
            snwink:134,
            caveman:135,
            dino:135,
            cavewoman:135,
            cavework:135,
            cavebeard:135,
            caveclothes:135,
            torch:135,
            spear:135,
            rocksmash:135,
            cavehair:135,
            boneswing:135,
            wallart:135,
            stickfire:135,
            cavebeard2:135,
            moonb:136,
            dance1:137,
            dance2:137,
            dance3:137,
            dance4:137,
            dance5:137,
            dance6:137,
            dance7:137,
            dance8:137,
            dance9:137,
            dance10:137,
            dance11:137,
            kpesneeze:138,
            kpeshy:138,
            kpeshame:138,
            kpejoy:138,
            kpeglare:138,
            kpefit:138,
            kpedots:138,
            kpedizzy:138,
            kpeclap:138,
            kpeangry:138,
            kpedance:138,
            kpepop:138,
            aplus:139,
            bowtie:139,
            brain:139,
            coder:139,
            gates:139,
            nglasses:139,
            nsci:139,
            phone:139,
            read:139,
            calc:139,
            backpack:141,
            daycare:141,
            gts:141,
            punished:141,
            rubber:141,
            schoolgirl:141,
            sbell:141,
            studying:141,
            tabsc:141,
            teacher2:141,
            writing:141,
            pconfused:143,
            pcrying:143,
            pcute:143,
            pdead:143,
            pfury:143,
            pgiggle:143,
            pglare:143,
            pjump:143,
            pmanic:143,
            punched:143,
            pshades:143,
            pshy:143,
            psleepy:143,
            pthink:143,
            dove:145,
            dove2:145,
            dove3:145,
            hglass:145,
            phair1:145,
            phair2:145,
            phair3:145,
            rbe:145,
            reggae:145,
            kccrying:146,
            kcdizzy:146,
            kceek:146,
            kcglare:146,
            kclook:146,
            kcsad:146,
            kcsmug:146,
            kctongue:146,
            kcwink:146,
            carveduh:147,
            carvegrin:147,
            carvescream:147,
            carvesly:147,
            carvesmile:147,
            dracula:147,
            grim2:147,
            pknhide:147,
            vampire:147,
            sixeyes:148,
            bat2:148,
            blackcat:148,
            blackwidow:148,
            ghost2:148,
            hockeymask:148,
            plant:148,
            bloodyknife:148,
            scarecrow:148,
            kdcheer:149,
            kdcrazy:149,
            kddead:149,
            kdfit:149,
            kdglare:149,
            kdsad:149,
            kdshocked:149,
            kdsleepy:149,
            kdsmile:149,
            kdtired:149,
            kdwoo:149,
            bot2:150,
            bot3:150,
            bot4:150,
            bot5:150,
            manga1:151,
            manga2:151,
            manga3:151,
            manga4:151,
            manga5:151,
            manga6:151,
            manga7:151,
            manga8:151,
            manga9:151,
            manga10:151,
            manga11:151,
            manga12:151,
            manga13:151,
            manga14:151,
            manga15:151,
            manga16:151,
            manga17:151,
            goldb:153,
            bars:153,
            bar:153,
            goldstar:153,
            smcry:154,
            smgrin:154,
            smlaugh:154,
            smredface:154,
            smsad:154,
            smshocked:154,
            smsleepy:154,
            smtongue:154,
            smmad:154,
            smcool:154,
            resurprised:155,
            resmirk:155,
            resleepy:155,
            resad:155,
            reredface:155,
            relaugh:155,
            reglare:155,
            recry:155,
            recool:155,
            reangry:155,
            renose:155,
            reback:155,
            sabiggrin:156,
            saconfused:156,
            sacry:156,
            saglare:156,
            saredface:156,
            sasad:156,
            sastraightface:156,
            sasurprised:156,
            satongue:156,
            sawink:156,
            spartayell:157,
            getready:157,
            helmet3:157,
            soldier:157,
            spants:157,
            spartafight:157,
            spartan:157,
            spartan2:157,
            truewar:157,
            xerxes:157,
            duh:158,
            doh2:158,
            calendar:160,
            celebration:160,
            champagne2:160,
            champagneback:160,
            clink2:160,
            firework1:160,
            firework2:160,
            nyball:160,
            nyhat:160,
            nykiss:160,
            nyparty:160,
            sparkler2:160,
            canangel:161,
            canbounce:161,
            cancontempt:161,
            canfury:161,
            canoo:161,
            canshifty:161,
            canthink:161,
            cantwitch:161,
            canum:161,
            canun:161,
            crosshair:164,
            folder:164,
            footprints:164,
            headset:164,
            keyhole:164,
            keypad:164,
            peeking:164,
            radar:164,
            spydrink:164,
            spyeye:164,
            spying:164,
            spypaper:164,
            spyrope:164,
            kduckback:165,
            kduck1:165,
            kduck2:165,
            kduck3:165,
            kduck4:165,
            kduck5:165,
            kduck6:165,
            kduck7:165,
            kduck8:165,
            kduck9:165,
            kduck10:165,
            kduck11:165,
            kduck12:165,
            heartfx:166,
            heartfx2:166,
            heartfx3:166,
            anonmask:167,
            beads:167,
            brazilboom:167,
            carniphant:167,
            cjester:167,
            cmask:167,
            flowersquirt:167,
            headdress:167,
            kreu:167,
            shakeit:167,
            wannasamba:167,
            yeayea:167,
            cjester2:167,
            cbird:167,
            cangel:167,
            action:169,
            admission:169,
            booth:169,
            cameraman:169,
            director:169,
            drink2:169,
            film:169,
            filmroll:169,
            popcorn:169,
            pose:169,
            tickets:169,
            mangel:170,
            mbat:170,
            mbear:170,
            mchick:170,
            mdrip:170,
            mfish:170,
            mglare:170,
            kat1:171,
            kat2:171,
            kat3:171,
            kat4:171,
            kat5:171,
            kat6:171,
            kat7:171,
            kat8:171,
            kat9:171,
            kat10:171,
            katback:171,
            typing1:172,
            ksheep1:173,
            ksheep2:173,
            ksheep3:173,
            ksheep4:173,
            ksheep5:173,
            ksheep6:173,
            ksheep7:173,
            ksheep8:173,
            ksheep9:173,
            ksheep10:173,
            ksheepback:173,
            pulsefxback:174,
            bbclap:175,
            bbconfused:175,
            bbcry:175,
            bbfit:175,
            bbglare:175,
            bbhug:175,
            bblaugh:175,
            bboops:175,
            bbpout:175,
            bbwink:175,
            bbback:175,
            fzangel:177,
            fzback:177,
            fzbiggrin:177,
            fzcool:177,
            fzcrazy:177,
            fzd:177,
            fzdance:177,
            fzsad:177,
            fzstretch:177,
            fztongue:177,
            fztwirl:177,
            spiralfx2:178,
            crazyn:179,
            nblood:179,
            nbroken:179,
            ndoc:179,
            nlist:179,
            nmask:179,
            nne:179,
            noxy:179,
            nsurg:179,
            megap:180,
            volume:180,
            tooloud:180,
            canthear:180,
            playbtn:180,
            kbeeback:181,
            kbeeclap:181,
            kbeecry:181,
            kbeed:181,
            kbeedance:181,
            kbeefedup:181,
            kbeejoy:181,
            kbeemad:181,
            kbeepunch:181,
            kbeexx:181,
            kbeeyay:181,
            vortexfx2:182,
            ballchain:183,
            bobby:183,
            copstop:183,
            cracker:183,
            cuffs:183,
            gavel:183,
            handsair:183,
            jailnumber:183,
            mugshot:183,
            prisoner:183,
            dripclap:185,
            dripdance:185,
            dripeek:185,
            dripfit:185,
            dripglare:185,
            driphehe:185,
            driphello:185,
            driphug:185,
            driplaugh:185,
            dripsad:185,
            dripshocked:185,
            driptired:185,
            dripxd:185,
            dripyell:185,
            moustache1:186,
            moustache2:186,
            moustache3:186,
            moustache4:186,
            moustache5:186,
            moustache6:186,
            moustache7:186,
            moustache8:186,
            moustache9:186,
            bronzem:189,
            goldm:189,
            oboxing:189,
            ocycling:189,
            odiving:189,
            ogymnastics:189,
            ohurdles:189,
            orowing:189,
            orunning:189,
            oswimming:189,
            otennis:189,
            otorch:189,
            ovolleyball:189,
            silverm:189,
            oarchery:189,
            obasketball:189,
            ofencing:189,
            ohockey:189,
            aliens:190,
            alilaugh:190,
            alidead:190,
            aliclap:190,
            alid:190,
            alilove:190,
            aliscratch:190,
            alitalk:190,
            alicry:190,
            alitongue:190,
            aliyay:190,
            aliback:190,
            bheartb:193,
            kpigangry:195,
            kpigback:195,
            kpigball:195,
            kpigfraz:195,
            kpiglove:195,
            kpigmad:195,
            kpigmud:195,
            kpigpals:195,
            kpigsleep:195,
            kpigsnoot:195,
            kpigwrite:195,
            pclubs:196,
            pobluff:196,
            pochips:196,
            pod:196,
            pogirl:196,
            poplayer:196,
            povip:196,
            powin:196,
            poyay:196,
            pspades:196,
            pdiamonds:196,
            phearts:196,
            poback:197,
            pocall:197,
            poclap:197,
            pocry:197,
            poeat:197,
            pofan:197,
            poglasses:197,
            pohay:197,
            pomane:197,
            ponyd:197,
            powhip:197,
            clockfx2:198,
            clockfx3:198,
            clockfx4:198,
            dropworry:199,
            dropumb:199,
            dropscratch:199,
            droprub:199,
            drophey:199,
            dropeat:199,
            dropdance:199,
            dropclap:199,
            dropback:199,
            spd:201,
            spfrus:201,
            spyay:201,
            spkiss:201,
            splap:201,
            splove:201,
            spvamp:201,
            spwrite:201,
            spxmas:201,
            sppup:201,
            spback:201,
            gifts:-3,
            vbat:202,
            vbheart:202,
            vblood:202,
            vcoffin:202,
            vcross:202,
            vfangs:202,
            vglamour:202,
            vrip:202,
            vstake:202,
            vtongue:202,
            clcool:204,
            cld:204,
            cleek:204,
            clgrin:204,
            clmad:204,
            clsad:204,
            clsmile:204,
            clsweat:204,
            clwink:204,
            clx:204,
            bearer:205,
            disappear:205,
            dwarf:205,
            goblin2:205,
            queenelf:205,
            sneak:205,
            thering:205,
            warrior:205,
            wizzard:205,
            1066:207,
            agreement:207,
            arrow:207,
            burnt:207,
            dwarf2:207,
            dwarfz:207,
            elve2:207,
            goblin3:207,
            newton:207,
            pile:207,
            kmcheer:210,
            kmcry:210,
            kmeyerub:210,
            kmfit:210,
            kmfrustrate:210,
            kmglare:210,
            kmgrouch:210,
            kmhide:210,
            kmhug:210,
            kmlaugh:210,
            kmshock:210,
            kmshuffle:210,
            kmsleepy:210,
            kmsmile:210,
            kmback:210,
            bighair:211,
            bigphone:211,
            boombox:211,
            cassette:211,
            dance80:211,
            dj80:211,
            hoverboard:211,
            joystick:211,
            skate:211,
            slacker1:211,
            slacker2:211,
            poi:211,
            thermochrome:211,
            timemachine:211,
            zombie1:213,
            zombie2:213,
            zombie3:213,
            zombie4:213,
            survivor1:213,
            survivor2:213,
            survivor3:213,
            survivor4:213,
            bloodface:213,
            deadup:213,
            zombieback:213,
            blush:214,
            comb:214,
            eyeliner:214,
            lipgloss:214,
            lipstick1:214,
            lipstick2:214,
            makeupface:214,
            nailpolish:214,
            perfume:214,
            purse:214,
            kharrow:215,
            khbub:215,
            khcupid:215,
            kheartb:215,
            kheyes:215,
            khhug:215,
            khhurt:215,
            khily:215,
            khkiss:215,
            khlips:215,
            khmadly:215,
            khring:215,
            khroses:215,
            kmoback:216,
            kmoblow:216,
            kmod:216,
            kmodance:216,
            kmofrus:216,
            kmonehneh:216,
            kmorage:216,
            kmoredface:216,
            kmostare:216,
            kmoteeth:216,
            kmoun:216,
            kmowhistle:216,
            kmowonder:216,
            nuclearb:217,
            barber:218,
            mirror2:218,
            shave:218,
            shair1:218,
            shair2:218,
            shair3:218,
            shair4:218,
            shair5:218,
            shair6:218,
            shair7:218,
            bees:219,
            birdy:219,
            butterflys:219,
            flohat:219,
            flohide:219,
            flowerbed:219,
            flowers:219,
            floshow:219,
            inflower:219,
            rainbow2:219,
            springhat:219,
            watercan:219,
            watercan2:219,
            bemused:220,
            cross:220,
            tick:220,
            placard:220,
            voting:220,
            voting2:220,
			hands2:221,
            pointing:221,
            prosper:221,
            peace2:221,
            notlistening:221,
            heehee:221,
            hearno:221,
            daydreaming:221,
            cutthroat:221,
            callme:221,
            crossed:221,
            highfive:221,
            chickwalk:222,
            eggnod:222,
            eggbroke:222,
            stripegg:222,
            eggwink:222,
            eggsleep:222,
            bunnyears:222,
            eggtongue:222,
            basket2:222,
            kfoxbino:225,
            kfoxcry:225,
            kfoxd:225,
            kfoxggl:225,
            kfoxinl:225,
            kfoxpsy:225,
            kfoxshades:225,
            kfoxsleep:225,
            kfoxtant:225,
            kfoxtwag:225,
            kfoxwhat:225,
            kwangry:226,
            kwbell:226,
            kwcry:226,
            kwd:226,
            kwfrus:226,
            kwlaugh:226,
            kwlove:226,
            kwmad:226,
            kwnod:226,
            kwscratch:226,
            kwsleepy:226,
            kwswt:226,
            kwwhat:226,
            kwyay:226,
            skannoyed:227,
            skd:227,
            skdead:227,
            skfrus:227,
            skgrr:227,
            skoo:227,
            sksad:227,
            sksix:227,
            sksmile:227,
            skwink:227,
            skback:227,
            beachdrink:229,
            beachvolley:229,
            coconut:229,
            crab2:229,
            dolphin2:229,
            flipflops:229,
            sandcastle:229,
            seatree:229,
            shell:229,
            hair2f1:230,
            hair2f2:230,
            hair2f3:230,
            hair2f4:230,
            hair2f5:230,
            hair2f6:230,
            hair2f7:230,
            hair2f8:230,
            hair2f9:230,
            hair2f10:230
        };
        public static var IsGroup = {
            126:1,
            130:1,
            134:1,
            136:1,
            140:1,
            148:1,
            150:1,
            152:1,
            156:1,
            162:1,
            176:1,
            180:1,
            184:1,
            188:1,
            192:1,
            194:1,
            200:1,
            206:1,
            220:1,
            224:1,
            238:1,
            246:1,
            252:1,
            0x0100:1
        };
		public static var SuperPowers = {};
		public static var SuperPawns = {};
        public static var pss = (((((((("powers" + ",allpowers,topman,subhide,mod8,zoom,nofollow,invert,mirror,noaudies,reghide,nopc,tempmod,hat,red,green,blue,light,heart,shuffle,animate,square,nameglow,cycle,hexagon,clear,boot,octogram,show,superkick,invisible,pink,31") + ",guestself,sinbin,diamond,purple,ttth,hands,hairm,hairf,fade,gag,costumes,six,dood,angel,mute,radio,fruit,sport,num,hush,halloween,anime,status,thanksgiving,snowy,christmas,count,stick,dx,tempmem,valentine,63") + ",blueman,party,irish,flashrank,easter,nopm,banish,circus,gkaoani,military,gline,bump,gkaliens,scifi,supporter,tempown,gcontrol,tickle,sea,silly,blastpro,flag,blastban,independence,blastde,summer,bad,rapid,horror,mint,blastkick,everypower") + ",winter,adventure,feast,single,link,shocker,fairy,namecolor,gkbear,angry,gscol,ugly,love,barge,gkkitty,fantasy,announce,hero,rankpool,spin,animal,music,gkpanda,unwell,events,zap,sins,outfit,wildwest,work,banpool,127") + ",beach,candy,gback,zodiac,flower,space,snakeban,stoneage,spaceban,dance,kpeng,nerd,matchban,school,silentm,punch,away,peace,kchick,carve,spooky,kdog,bot,manga,mazeban,gold,snowman,reindeer,santa,sparta,dunce,159,") + "newyear,can,codeban,magicfx,spy,kduck,heartfx,carnival,topspin,movie,monster,kat,typing,ksheep,pulsefx,blobby,reverse,fuzzy,spiralfx,nursing,gsound,kbee,vortexfx,jail,zip,drip,moustache,whirlfx,doodlerace,olympic,aliens,191,") + "matchrace,burningheart,snakerace,kpig,poker,pony,clockfx,drop,spacewar,speech,vampyre,treefx,claus,quest,lang,quest2,glitterfx,xavi,kmouse,eighties,") + "foe,zombie,makeup,kheart,kmonkey,nuclear,stylist,spring,vote,hands2,eggs,223,hearts,kfox,kcow,sketch,led,seaside,hair2f,statusglow");
        public static var Pawns;
        public static var PawnsR;
        public static var pssh = new Object();
        public static var pssa:Array;
        public static var smi;
        public static var smArray:Array;
        public static var tsmi = "";
        public static var smih = new Object();
        public static var smia:Array;
        public static var Glitters = {
            test1:1,
            test2:2,
            bounce:2,
            led:1,
            beams:1,
            blood:1,
            equ:1,
            glitter:2,
            lips:2,
            up:2,
            down:2,
            walk:2,
            snow:2,
            xmas:1,
            snowy:1
        };
        public static var f_Lobby:Number = 2;
        public static var f_Group:Number = 64;
        public static var f_MembersOnly = 128;
        public static var f_MembersOnly2 = 0x100000;
        public static var f_Live = 0x200000;
        public static var f_NoList = 0x0200;
        public static var f_NoSmilies:Number = 0x0800;
        public static var f_DefNoSound = 131072;
		
        public static function AddToSuperP(_arg_1:*, _arg_2:*){
            var _local_3:*;
            var _local_4:*;
            _arg_1 = xatlib.xInt(_arg_1);
            var _local_5:* = _arg_2["n"].split(",");
            SuperPowers[_arg_1] = [];
            for (_local_4 in _local_5) {
                SuperPowers[_arg_1].push(xatlib.xInt(_local_5[_local_4]));
            };
            _local_5 = _arg_2["s"].split(",");
            for (_local_4 in _local_5) {
                _local_3 = _local_5[_local_4];
                xconst.smi = (xconst.smi + ("," + _local_3));
                xconst.smia.push(_local_3);
                xconst.smih[_local_3] = true;
                if (_local_4 > 0){
                    xconst.topsh[_local_3] = _arg_1;
                } else {
                    xconst.pssh[_local_3] = _arg_1;
                    xconst.pssa[(_arg_1 + 1)] = _local_3;
                };
            };
            _local_5 = _arg_2["p"].split(",");
            for (_local_4 in _local_5) {
                SuperPawns[_local_5[_local_4]] = _arg_1;
            };
        }
        public static function xconstInit(){
            var _local1:*;
            var _local2:*;
            var _local3:*;
            var _local4:*;
            var _local5:*;
            _local1 = 70;
            while (_local1 <= 120) {
                IsGroup[_local1] = 1;
                _local1 = (_local1 + 2);
            };
            StringTable = stab.split("£");
            HelpTable = htab.split("£");
            ActionTable = {};
            ActionNames = [];
            _local1 = xtab.split("£");
            BuildActiontable(_local1, 0);
            name1 = n1.split(",");
            name2 = n2.split(",");
            pool1 = p1.split(",");
            pool2 = p2.split(",");
            kssa = kss.split(",");
            backsR = ReverseObj(backs);
            effectsR = ReverseObj(effects);
            colorc["-"] = 1;
            colorc["+"] = 1;
            topsh["6"] = 43;
            topsh["3d"] = 42;
            for (_local2 in global.mt) {
                topsh[_local2] = global.mt[_local2];
            };
            pssa = pss.split(",");
            _local1 = 232;
            while (_local1 <= (todo.PWR_MAX_TRADE + 2)) {
				if (!pssa[(_local1 + 1)]){
					pssa[(_local1 + 1)] = _local1;
				};
                _local1++;
            };
            _local3 = 0;
            while (_local3 < pssa.length) {
                pssh[pssa[_local3]] = (((_local3 > 1)) ? (_local3 - 1) : (_local3 - 2));
                _local3++;
            };
            smi = ("hi,meh,ugh,a,sry,crs,un,d,scn,nod,gagged,nme,swt,roll,rofl,chkl,inlove,blk,xp,eyes,tired,smirk,ill,dead,hello,yum,think,mischief,zip2,puke,yawn,swear,cry2,what,omg,o_o,goo,smirk2,beye,wary,shock,xd,cyc,wt,chew,contempt,fedup,aghast,look,spin2,tipsy,twitch,shifty,ashamed,pty,sad,rolling,no,jolly,annoyed,astonished,evil,sinister,sour,um,dream,memory,babythrow,candyeat,cute,flowerthrow,gloomy,hey,hula,loving,meloneat,shadesoff,stressing,waiting,ugc,hearts2" + ",applause,donttalk,joyful,smug,victory,blowkiss,dull,medmask,sob,wacky,confounded,ecstatic,ok,sweat,wailing,content,farewell,pensive,tearhair,weary,daydream,flustered,point,tmi,whatever,furious,sarcastic,toj,whistling,depressed,here,screaming,ttm,zany,desire,hih,sidetear,unamused,dollar,idc,slap,unreal,deal,ca,censor,dab,dumb,dwi,flushed,gal,grump,kisy,none,scared,steaming,uhuh" + ",^_^,-_-");
            for (_local4 in topsh) {
                smi = (smi + ("," + _local4));
            };
            if (global.ms != undefined){
                smi = (smi + global.ms);
            };
            smi = (smi + ",peach,xana,x,chest,gst,alien,bby,bot1,tox,8ball,eye,kirb,pm,pmg,inv,inv2,inv3,sonic,shadow,mario,luigi,mushroom,yoshi,countb,ness,smashball,mephiles,tri,lucario,nights,arbiter,link,mewtwo,xj9,hk,lolwut,kermit,beaker,beast,dv,homer,3tomoe,mangekyou,pikachu,pball,wwe,sm,a1,nko,x3,dog,cat,pig,mk,penguin,panda,bear,cc,ccc,cotton,pie,c,b,o,i,t,mo,so,sb,oo,p,ph,yt,dmd,bin,ush,ipod,ip,sun,rain,r,f,li,l,u,y,n,grl,boy,scb,bio,rad,pgm,mgp,ao,star,note,hex,yy,moon,rubik,cir,cdy,deer,snta,g,sman,xday,xtre,xstk,mtoe,hly,egg,ghat,clover,stickman,stickman2,stickman3,stickairguitar,stickkungfu,stickangry,stickymca,danny,turkey,ss,qbone,mc,lb,mario8,nop,okp,mate,amy,mouser");
            smi = (smi + ((("," + kss.toLowerCase()) + ",") + pss));
            smArray = sa.split(",");
            _local3 = 0;
            while (_local3 < smArray.length) {
                if (smArray[_local3] == "M"){
                    smArray[_local3] = -1;
                };
                if (smArray[_local3] == "T"){
                    smArray[_local3] = -2;
                };
                if (smArray[_local3] < 0){
                    tsmi = (tsmi + (smArray[(_local3 - 1)] + ","));
                };
                _local3++;
            };
            smi = (tsmi + smi);
            smia = smi.split(",");
            _local3 = 0;
            while (_local3 < smia.length) {
                smih[smia[_local3]] = true;
                _local3++;
            };
            if (global.mg != undefined){
                for (_local5 in global.mg) {
                    Glitters[_local5] = global.mg[_local5];
                };
            };
        }
        public static function ST(_arg1:Number, _arg2:*=undefined, _arg3:*=undefined, _arg4:*=undefined, _arg5:*=undefined):String{
            var _local6:String = StringTable[_arg1];
            if (_arg2 != undefined){
                _local6 = ((_local6.slice(0, _local6.indexOf("$1")) + _arg2) + _local6.slice((_local6.indexOf("$1") + 2)));
            };
            if (_arg3 != undefined){
                _local6 = ((_local6.slice(0, _local6.indexOf("$2")) + _arg3) + _local6.slice((_local6.indexOf("$2") + 2)));
            };
            if (_arg4 != undefined){
                _local6 = ((_local6.slice(0, _local6.indexOf("$3")) + _arg4) + _local6.slice((_local6.indexOf("$3") + 2)));
            };
            if (_arg5 != undefined){
                _local6 = ((_local6.slice(0, _local6.indexOf("$4")) + _arg5) + _local6.slice((_local6.indexOf("$4") + 2)));
            };
            return (_local6);
        }
        public static function CreateST(){
            var _local1:int;
            var _local2:*;
            var _local4:*;
            var _local3:int;
            var _local5:int;
            _local2 = xatlib.xJSONdecode(todo.LangText, false);
            if (!_local2){
                return;
            };
			
			/* for new lang file shit
			_local_2 = _local_2["box"];
			if (!_local_2){
				return;
			};
			*/
			
            _local5 = _local2[86];
            delete _local2[86];
            BuildActiontable(_local2, 2000);
            for (_local4 in _local2) {
                if (_local4 < 1000){
                    StringTable[_local4] = _local2[_local4].split("CR").join("\n");
                } else {
                    if (_local4 < 2000){
                        if (_local3 == 0){
                            HelpTable = [];
                            _local3 = 1;
                        };
                        HelpTable[(_local4 - 1000)] = _local2[_local4];
                    };
                };
            };
            todo.LangText = undefined;
            if ((_local5 & 1)){
                main.utabsmc.CreateVisitorsTabs();
                if (main.mcgetachat.lc){
                    main.mcgetachat.SetText(xconst.ST(main.mcgetachat.lc));
                };
                network.SetNetworkState(network.NetworkState, network.NetworkTimeout);
            };
        }
        public static function MakeBads(_arg_1:*=null){
            var _local_2:*;
            var _local_3:*;
            var _local_6:*;
            var _local_7:*;
            badwords = bw.split(",");
            var _local_4:* = StringTable[163].split(",");
            _local_2 = 0;
            while (_local_2 < _local_4.length) {
                if (_local_4[_local_2].length > 2){
                    badwords.push(_local_4[_local_2]);
                };
                _local_2++;
            };
            if (_arg_1){
                _local_6 = {};
                _arg_1 = _arg_1.split(",");
                _local_2 = 0;
                while (_local_2 < _arg_1.length) {
                    if (_arg_1[_local_2].length > 3){
                        badwords.push(_arg_1[_local_2]);
                        _local_6[_arg_1[_local_2]] = true;
                    };
                    _local_2++;
                };
                todo.gconfig["g90"] = _local_6;
            } else {
                if (todo.gconfig["g90"]){
                    for (_local_2 in todo.gconfig["g90"]) {
                        badwords.push(_local_2);
                    };
                };
            };
            highwords = {};
            var _local_5:* = "0";
            if (((todo.Macros["mark"]) && (todo.HasPowerA(todo.w_Powers, xconst.pssh["pcback"])))){
                _local_7 = todo.Macros["mark"].split(",");
                _local_2 = 0;
                while (_local_2 < _local_7.length) {
                    if (_local_7[_local_2]){
                        _local_3 = _local_7[_local_2].split("#");
                        if (_local_3[0]){
                            badwords.push(_local_3[0]);
                            if (_local_3[1]){
                                _local_5 = _local_3[1];
                            };
                            highwords[_local_3[0]] = _local_5;
                        };
                    };
                    _local_2++;
                };
            };
        }
        public static function ReverseObj(_arg1){
            var _local3:*;
            var _local2:* = new Object();
            for (_local3 in _arg1) {
                _local2[_arg1[_local3]] = _local3;
            };
            return (_local2);
        }
        public static function BuildActiontable(_arg1, _arg2){
            var _local3:*;
            var _local4:int;
            var _local5:int;
            if (!_arg1){
                return;
            };
            _local5 = 0;
            while (_local5 < 100) {
                _local3 = _arg1[(_local5 + _arg2)];
                if (!_local3){
                } else {
                    _local3 = _local3.split(",");
                    if (_arg2 == 0){
                        ActionNames[(_local5 + 1)] = _local3[0];
                    };
                    ActionTable[_local3[0]] = (_local5 + 1);
                    _local4 = 1;
                    while (_local4 < 100) {
                        if (!_local3[_local4]){
                            break;
                        };
                        ActionTable[_local3[_local4]] = (_local5 + 1);
                        _local4++;
                    };
                };
                _local5++;
            };
        }

    }
}//package 
